# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R

matrix:
  include:
  - r: release
    os: osx
  - r: release
    os: linux
    after_success: travis_wait Rscript -e 'covr::codecov()'
  - r: devel
    os: linux


sudo: false
cache: packages
warnings_are_errors: false
r_check_args: "--timings --as-cran"
script:
  - |
    R CMD build .
    travis_wait 20 R CMD check --no-vignettes bayesmove*tar.gz

notifications:
  email:
    on_success: change
    on_failure: change
